---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoë.
--- DateTime: 11/04/2022 18:06
---

local events = {};

function events:ADDON_LOADED(Addon)
    if Addon == "CDDetector" then
        SELECTED_CHAT_FRAME:AddMessage("CDDetector loaded")
        if CDDCustomSpells == nil then
            CDDCustomSpells = {}
        end

        for k, v in pairs(CDDCustomSpells) do
            CDDetector.Spells[k] = v;
            CDDetector.CustomSpells = CDDetector.CustomSpells+1;
        end
    end
end

function events:COMBAT_LOG_EVENT_UNFILTERED()
    local _, subevent, _, _, sourceName, _, _, _, destName, _, _, spellID, spellName = CombatLogGetCurrentEventInfo()

    if subevent ~= "SPELL_CAST_SUCCESS" then return nil end
    if not (CDDetector.Spells[spellID]) then return nil end
    if (CDDetector.Spells[spellID] == "Haste" or CDDetector.Spells[spellID] == "CR") then
        if not (UnitInRaid(sourceName) or UnitInParty(sourceName)) then
            return nil
        end
    end

    if destName ~= nil then
        CDDetector.utils.DoLog(subevent..", "..spellName.." ("..spellID.."), "..sourceName..", "..destName, 2)
    else
        CDDetector.utils.DoLog(subevent..", "..spellName.." ("..spellID.."), "..sourceName, 2)
    end

    local channel = "SAY"
    if IsInGroup() then channel = "PARTY" end
    if IsInRaid() then channel = "RAID" end
    if IsInInstance() then channel = "INSTANCE_CHAT" end

    if UnitIsUnit(sourceName, "pet") then
        sourceName = UnitName("player") -- replace pet name with player name
    end
    if IsInGroup() then
        for i = 1, GetNumGroupMembers() do
            if UnitIsUnit(("%spet%i"):format(channel:lower(), i), sourceName) then
                sourceName = ("%s"):format(UnitName(("%s%i"):format(channel:lower(), i))) -- replace pet name with player name
                break
            end
        end
    end

    if CDDetector.Spells[spellID] == "CR" then
        SendChatMessage("CD Detector: "..sourceName.." cast Combat Resurrection spell "..GetSpellLink(spellID).." on "..destName, channel)
    end
    if CDDetector.Spells[spellID] == "Haste" then
        SendChatMessage("CD Detector: "..sourceName.." cast Haste spell "..GetSpellLink(spellID), channel)
    end
    if CDDetector.Spells[spellID] == "Hostile_Untargeted" then
        SendChatMessage("CD Detector: "..sourceName.." cast Hostile spell "..GetSpellLink(spellID), channel)
    end
    if CDDetector.Spells[spellID] == "Hostile_Targeted" then
        SendChatMessage("CD Detector: "..sourceName.." cast Hostile spell "..GetSpellLink(spellID).." on "..destName, channel)
    end
    if CDDetector.Spells[spellID] == "Notable_Untargeted" then
        SendChatMessage("CD Detector: "..sourceName.." cast Notable spell "..GetSpellLink(spellID), channel)
    end
    if CDDetector.Spells[spellID] == "Notable_Targeted" then
        SendChatMessage("CD Detector: "..sourceName.." cast Notable spell "..GetSpellLink(spellID).." on "..destName, channel)
    end
    if CDDetector.Spells[spellID] == "Test" then
        CDDetector.utils.DoLog("CD Detector: "..sourceName.." cast Test spell "..GetSpellLink(spellID), 1)
    end
end



CDDetector.events = events;