---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoë.
--- DateTime: 14/04/2022 20:22
---

_G.CDDetector = {
    DebugLevel = 0,
    SpellTypes = {
      Haste = true,
      CR = true,
      Hostile_Targeted = true,
      Hostile_Untargeted = true
    },
    Spells = {
        [2825] = "Haste", -- Bloodlust
        [32182] = "Haste", -- Heroism
        [80353] = "Haste", -- Time Warp
        [264667] = "Haste", -- Primal Rage, Direct
        [272678] = "Haste", -- Primal Rage, Command Pet
        [146613] = "Haste", -- Drums of Rage
        [178207] = "Haste", -- Drums of Fury
        [230935] = "Haste", -- Drums of the Mountain
        [256740] = "Haste", -- Drums of the Maelstrom
        [309658] = "Haste", -- Drums of Deathly Ferocity
        [293076] = "Haste", -- Mallet of Thunderous Skins
        [20484] = "CR", -- Rebirth
        [61999] = "CR", -- Raise Ally
        [20707] = "CR", -- Soulstone
        [265116] = "CR", -- Unstable Temporal Time Shifter
        [348477] = "CR", -- Disposable Spectrophasic Reanimator
        [240446] = "Hostile_Untargeted", -- Explosion
        [116670] = "Test" -- Vivify
    },
    CustomSpells = 0,
    frame = CreateFrame("Frame")
}

